export type MarketBoardSnapshot = {
    sectorCode: string
    sectorName: string
    latestPrice: number | null
    changeRate: number | null
    mainNetInflow: number | null
}

export type MarketStockSnapshot = {
    symbol?: string
    stockCode: string
    stockName: string
    sectorCode: string
    sectorName: string
    openPrice: number | null
    closePrice: number | null
    highPrice: number | null
    lowPrice: number | null
    amount: number | null
    changeRate: number | null
    mainNetInflow: number | null
}

export const representativeSinaStocks: MarketStockSnapshot[] = [
    {
        symbol: 'sz300308',
        stockCode: '300308',
        stockName: '中际旭创',
        sectorCode: 'AI_COMPUTE',
        sectorName: 'AI算力链',
        openPrice: null,
        closePrice: null,
        highPrice: null,
        lowPrice: null,
        amount: null,
        changeRate: null,
        mainNetInflow: null,
    },
    {
        symbol: 'sz300502',
        stockCode: '300502',
        stockName: '新易盛',
        sectorCode: 'AI_COMPUTE',
        sectorName: 'AI算力链',
        openPrice: null,
        closePrice: null,
        highPrice: null,
        lowPrice: null,
        amount: null,
        changeRate: null,
        mainNetInflow: null,
    },
    {
        symbol: 'sh603019',
        stockCode: '603019',
        stockName: '中科曙光',
        sectorCode: 'AI_INFRA',
        sectorName: '算力基础设施',
        openPrice: null,
        closePrice: null,
        highPrice: null,
        lowPrice: null,
        amount: null,
        changeRate: null,
        mainNetInflow: null,
    },
    {
        symbol: 'sz300024',
        stockCode: '300024',
        stockName: '机器人',
        sectorCode: 'ROBOTICS',
        sectorName: '机器人',
        openPrice: null,
        closePrice: null,
        highPrice: null,
        lowPrice: null,
        amount: null,
        changeRate: null,
        mainNetInflow: null,
    },
    {
        symbol: 'sz002230',
        stockCode: '002230',
        stockName: '科大讯飞',
        sectorCode: 'AI_APP',
        sectorName: 'AI应用',
        openPrice: null,
        closePrice: null,
        highPrice: null,
        lowPrice: null,
        amount: null,
        changeRate: null,
        mainNetInflow: null,
    },
    {
        symbol: 'sh600519',
        stockCode: '600519',
        stockName: '贵州茅台',
        sectorCode: 'BLUECHIP',
        sectorName: '权重蓝筹',
        openPrice: null,
        closePrice: null,
        highPrice: null,
        lowPrice: null,
        amount: null,
        changeRate: null,
        mainNetInflow: null,
    },
    {
        symbol: 'sh601138',
        stockCode: '601138',
        stockName: '工业富联',
        sectorCode: 'AI_HARDWARE',
        sectorName: 'AI硬件',
        openPrice: null,
        closePrice: null,
        highPrice: null,
        lowPrice: null,
        amount: null,
        changeRate: null,
        mainNetInflow: null,
    },
    {
        symbol: 'sz002463',
        stockCode: '002463',
        stockName: '沪电股份',
        sectorCode: 'AI_HARDWARE',
        sectorName: 'AI硬件',
        openPrice: null,
        closePrice: null,
        highPrice: null,
        lowPrice: null,
        amount: null,
        changeRate: null,
        mainNetInflow: null,
    },
    {
        symbol: 'sh688256',
        stockCode: '688256',
        stockName: '寒武纪',
        sectorCode: 'AI_CHIP',
        sectorName: 'AI芯片',
        openPrice: null,
        closePrice: null,
        highPrice: null,
        lowPrice: null,
        amount: null,
        changeRate: null,
        mainNetInflow: null,
    },
    {
        symbol: 'sz300033',
        stockCode: '300033',
        stockName: '同花顺',
        sectorCode: 'AI_APP',
        sectorName: 'AI应用',
        openPrice: null,
        closePrice: null,
        highPrice: null,
        lowPrice: null,
        amount: null,
        changeRate: null,
        mainNetInflow: null,
    },
    {
        symbol: 'sz002415',
        stockCode: '002415',
        stockName: '海康威视',
        sectorCode: 'AI_VISION',
        sectorName: 'AI视觉',
        openPrice: null,
        closePrice: null,
        highPrice: null,
        lowPrice: null,
        amount: null,
        changeRate: null,
        mainNetInflow: null,
    },
    {
        symbol: 'sh601127',
        stockCode: '601127',
        stockName: '赛力斯',
        sectorCode: 'SMART_AUTO',
        sectorName: '智能汽车',
        openPrice: null,
        closePrice: null,
        highPrice: null,
        lowPrice: null,
        amount: null,
        changeRate: null,
        mainNetInflow: null,
    },
]

export const demoBoardFallback: MarketBoardSnapshot[] = [
    {
        sectorCode: 'AI_COMPUTE',
        sectorName: 'AI算力链',
        latestPrice: 1287.36,
        changeRate: 3.42,
        mainNetInflow: 486000000,
    },
    {
        sectorCode: 'ROBOTICS',
        sectorName: '机器人',
        latestPrice: 942.18,
        changeRate: 2.31,
        mainNetInflow: 268000000,
    },
    {
        sectorCode: 'AI_APP',
        sectorName: 'AI应用',
        latestPrice: 1058.44,
        changeRate: 1.68,
        mainNetInflow: 193000000,
    },
]

export const demoStockFallback: MarketStockSnapshot[] = [
    {
        stockCode: '300001',
        stockName: '示例科技',
        sectorCode: 'AI_COMPUTE',
        sectorName: 'AI算力链',
        openPrice: 18.72,
        closePrice: 19.08,
        highPrice: 19.22,
        lowPrice: 18.6,
        amount: 486000000,
        changeRate: 4.21,
        mainNetInflow: 98000000,
    },
    {
        stockCode: '300002',
        stockName: '示例智能',
        sectorCode: 'ROBOTICS',
        sectorName: '机器人',
        openPrice: 26.58,
        closePrice: 26.96,
        highPrice: 27.15,
        lowPrice: 26.4,
        amount: 532000000,
        changeRate: 2.84,
        mainNetInflow: 112000000,
    },
    {
        stockCode: '600003',
        stockName: '示例云算',
        sectorCode: 'AI_COMPUTE',
        sectorName: 'AI算力链',
        openPrice: 12.08,
        closePrice: 12.36,
        highPrice: 12.48,
        lowPrice: 12.02,
        amount: 215000000,
        changeRate: 2.49,
        mainNetInflow: 36000000,
    },
    {
        stockCode: '688004',
        stockName: '示例芯算',
        sectorCode: 'AI_COMPUTE',
        sectorName: 'AI算力链',
        openPrice: 45.1,
        closePrice: 46.12,
        highPrice: 46.58,
        lowPrice: 44.96,
        amount: 398000000,
        changeRate: 3.85,
        mainNetInflow: 87000000,
    },
]